<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public const PERMISSIONS = [
        // Stage 1
        'users.view',
        'users.manage',
        'roles.view',
        'branches.view',
        'branches.manage',
        'audit.view',
        'settings.manage',
        'dashboard.view',
        // Stage 2 — Zoho / customers / invoices / debtors
        'zoho.configure',
        'zoho.view',
        'zoho.sync',
        'customers.view',
        'customers.manage',
        'invoices.view',
        'debtors.view',
        'debtors.export',
        // Stage 3 — assignments / visits / routes / promises / notes / evidence / reports
        'assignments.view',
        'assignments.manage',
        'assignments.reassign',
        'assignments.cancel',
        'assignments.export',
        'visits.view',
        'visits.create',
        'visits.manage',
        'routes.view',
        'routes.manage',
        'promises.view',
        'promises.create',
        'promises.manage',
        'notes.view',
        'notes.create',
        'notes.manage',
        'evidence.view',
        'evidence.upload',
        'notifications.view',
        'reports.assignments',
        'reports.visits',
        'reports.promises',
        'collectors.view',
        'collectors.manage',
        'escalations.view',
        'escalations.manage',
        // Stage 4 — payments / receipts / wallets / reversals
        'payments.view',
        'payments.create',
        'payments.confirm',
        'payments.manage',
        'payments.export',
        'payments.retry_sync',
        'payments.reconcile',
        'receipts.view',
        'receipts.print',
        'receipts.manage',
        'wallets.view',
        'wallets.manage',
        'reversals.request',
        'reversals.approve',
        'payment_settings.manage',
        'handovers.view',
        'handovers.create',
        'handovers.submit',
        'handovers.review',
        'cashboxes.view',
        'cashboxes.manage',
        'cashbox_transfers.view',
        'cashbox_transfers.create',
        'cashbox_transfers.approve',
        'bank_deposits.view',
        'bank_deposits.manage',
        'cash_reconciliation.view',
        'cash_reconciliation.run',
        'cash_variances.view',
        'cash_variances.manage',
        'cash_adjustments.view',
        'cash_adjustments.manage',
        'custody_reversals.review',
        'customer_prefix_mapping.view',
        'customer_prefix_mapping.manage',
        'customer_prefix_mapping.apply',
        // Stage 5.2 — permanent ownership / branch Zoho payment mapping
        'customer_ownership.view',
        'customer_ownership.create',
        'customer_ownership.transfer',
        'customer_ownership.end',
        'temporary_assignments.view',
        'temporary_assignments.create',
        'temporary_assignments.cancel',
        'branch_payment_mapping.view',
        'branch_payment_mapping.manage',
        'branch_payment_mapping.validate',
        'ownership_conflicts.view',
        'ownership_conflicts.resolve',
        'receivables_dashboard.view',
        // Stage 6 — WhatsApp
        'whatsapp.view',
        'whatsapp.manage',
        'whatsapp.send_test',
        // Stage 7 — Ticketing / tasks / installations / SLA
        'tickets.view',
        'tickets.create',
        'tickets.update',
        'tickets.assign',
        'tickets.resolve',
        'tickets.close',
        'tickets.reopen',
        'tickets.view_all_branch',
        'tickets.view_all',
        'tasks.view',
        'tasks.create',
        'tasks.assign',
        'tasks.accept',
        'tasks.complete',
        'tasks.verify',
        'tasks.reassign',
        'tasks.cancel',
        'sla.manage',
        'installations.view',
        'installations.create',
        'installations.assign',
        'installations.update',
        'attachments.upload',
        'attachments.delete',
        'reports.support',
        'reports.technical',
        'reports.management',
        'whatsapp.ticket_intake',
        'whatsapp.staff_actions',
        'departments.manage',
        'ticket_types.manage',
        'task_templates.manage',
    ];

    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        foreach (self::PERMISSIONS as $permission) {
            Permission::findOrCreate($permission, 'web');
        }

        $superAdmin = Role::findOrCreate(User::ROLE_SUPER_ADMIN, 'web');
        $centralFinance = Role::findOrCreate(User::ROLE_CENTRAL_FINANCE, 'web');
        $branchManager = Role::findOrCreate(User::ROLE_BRANCH_MANAGER, 'web');
        $collector = Role::findOrCreate(User::ROLE_COLLECTOR, 'web');
        $auditor = Role::findOrCreate(User::ROLE_AUDITOR, 'web');

        $superAdmin->syncPermissions(self::PERMISSIONS);

        $centralFinance->syncPermissions([
            'users.view',
            'users.manage',
            'roles.view',
            'branches.view',
            'branches.manage',
            'audit.view',
            'settings.manage',
            'dashboard.view',
            'zoho.view',
            'zoho.sync',
            'customers.view',
            'customers.manage',
            'invoices.view',
            'debtors.view',
            'debtors.export',
            'assignments.view',
            'assignments.manage',
            'assignments.reassign',
            'assignments.export',
            'visits.view',
            'routes.view',
            'promises.view',
            'promises.manage',
            'notes.view',
            'evidence.view',
            'notifications.view',
            'reports.assignments',
            'reports.visits',
            'reports.promises',
            'collectors.view',
            'escalations.view',
            'payments.view',
            'payments.create',
            'payments.confirm',
            'payments.manage',
            'payments.export',
            'payments.retry_sync',
            'payments.reconcile',
            'receipts.view',
            'receipts.print',
            'receipts.manage',
            'wallets.view',
            'wallets.manage',
            'reversals.request',
            'reversals.approve',
            'payment_settings.manage',
            'handovers.view', 'handovers.create', 'handovers.submit', 'handovers.review',
            'cashboxes.view', 'cashboxes.manage', 'cashbox_transfers.view', 'cashbox_transfers.create', 'cashbox_transfers.approve',
            'bank_deposits.view', 'bank_deposits.manage', 'cash_reconciliation.view', 'cash_reconciliation.run',
            'cash_variances.view', 'cash_variances.manage', 'cash_adjustments.view', 'cash_adjustments.manage', 'custody_reversals.review',
            'customer_prefix_mapping.view',
            'customer_prefix_mapping.manage',
            'customer_prefix_mapping.apply',
            'customer_ownership.view', 'customer_ownership.create', 'customer_ownership.transfer', 'customer_ownership.end',
            'temporary_assignments.view', 'temporary_assignments.create', 'temporary_assignments.cancel',
            'branch_payment_mapping.view', 'branch_payment_mapping.manage', 'branch_payment_mapping.validate',
            'ownership_conflicts.view', 'ownership_conflicts.resolve', 'receivables_dashboard.view',
            'whatsapp.view', 'whatsapp.manage', 'whatsapp.send_test',
            // Stage 7
            'tickets.view', 'tickets.view_all', 'tickets.create', 'tickets.update',
            'tasks.view', 'tasks.create',
            'installations.view', 'installations.update',
            'reports.support', 'reports.management',
            'whatsapp.ticket_intake',
            'attachments.upload',
            'escalations.view',
        ]);

        $branchManager->syncPermissions([
            'users.view',
            'branches.view',
            'dashboard.view',
            'customers.view',
            'invoices.view',
            'debtors.view',
            'assignments.view',
            'assignments.manage',
            'assignments.reassign',
            'assignments.cancel',
            'assignments.export',
            'visits.view',
            'visits.manage',
            'routes.view',
            'routes.manage',
            'promises.view',
            'promises.manage',
            'notes.view',
            'notes.create',
            'notes.manage',
            'evidence.view',
            'notifications.view',
            'reports.assignments',
            'reports.visits',
            'reports.promises',
            'collectors.view',
            'escalations.view',
            'escalations.manage',
            'payments.view',
            'payments.create',
            'payments.confirm',
            'payments.manage',
            'payments.export',
            'payments.retry_sync',
            'receipts.view',
            'receipts.print',
            'receipts.manage',
            'wallets.view',
            'wallets.manage',
            'reversals.request',
            'reversals.approve',
            'handovers.view', 'handovers.review', 'cashboxes.view', 'cashboxes.manage',
            'cashbox_transfers.view', 'cashbox_transfers.create', 'cashbox_transfers.approve',
            'cash_reconciliation.view', 'cash_reconciliation.run', 'cash_variances.view', 'cash_variances.manage',
            'customer_ownership.view', 'customer_ownership.create', 'customer_ownership.transfer', 'customer_ownership.end',
            'temporary_assignments.view', 'temporary_assignments.create', 'temporary_assignments.cancel',
            'branch_payment_mapping.view', 'branch_payment_mapping.manage', 'branch_payment_mapping.validate',
            'ownership_conflicts.view', 'ownership_conflicts.resolve', 'receivables_dashboard.view',
            // Stage 7
            'tickets.view', 'tickets.create', 'tickets.update', 'tickets.assign',
            'tickets.resolve', 'tickets.close', 'tickets.reopen', 'tickets.view_all_branch',
            'tasks.view', 'tasks.create', 'tasks.assign', 'tasks.accept', 'tasks.complete',
            'tasks.verify', 'tasks.reassign', 'tasks.cancel',
            'sla.manage',
            'installations.view', 'installations.create', 'installations.assign', 'installations.update',
            'attachments.upload', 'attachments.delete',
            'reports.support', 'reports.technical', 'reports.management',
            'whatsapp.ticket_intake', 'whatsapp.staff_actions',
            'departments.manage',
            'whatsapp.view',
        ]);

        $collector->syncPermissions([
            'branches.view',
            'dashboard.view',
            'customers.view',
            'invoices.view',
            'assignments.view',
            'visits.view',
            'visits.create',
            'routes.view',
            'promises.view',
            'promises.create',
            'notes.view',
            'notes.create',
            'evidence.view',
            'evidence.upload',
            'notifications.view',
            'payments.view',
            'payments.create',
            'payments.confirm',
            'receipts.view',
            'receipts.print',
            'wallets.view',
            'reversals.request',
            'handovers.view', 'handovers.create', 'handovers.submit',
            'customer_ownership.view',
            'temporary_assignments.view',
            // Stage 7 — field tasks + limited tickets
            'tickets.view',
            'tasks.view', 'tasks.accept', 'tasks.complete',
            'attachments.upload',
            'whatsapp.staff_actions',
        ]);

        $auditor->syncPermissions([
            'users.view',
            'roles.view',
            'branches.view',
            'audit.view',
            'dashboard.view',
            'zoho.view',
            'customers.view',
            'invoices.view',
            'debtors.view',
            'assignments.view',
            'visits.view',
            'routes.view',
            'promises.view',
            'notes.view',
            'evidence.view',
            'reports.assignments',
            'reports.visits',
            'reports.promises',
            'collectors.view',
            'escalations.view',
            'payments.view',
            'payments.export',
            'receipts.view',
            'wallets.view',
            'handovers.view', 'cashboxes.view', 'cashbox_transfers.view', 'bank_deposits.view',
            'cash_reconciliation.view', 'cash_variances.view', 'cash_adjustments.view',
            // Stage 7 — view + reports
            'tickets.view', 'tickets.view_all_branch',
            'tasks.view',
            'installations.view',
            'reports.support', 'reports.technical', 'reports.management',
            'whatsapp.view',
        ]);
    }
}
