<?php

namespace Database\Seeders;

use App\Models\Tickets\SlaPolicy;
use App\Models\Tickets\TicketType;
use Illuminate\Database\Seeder;

class Stage7TicketTypeSeeder extends Seeder
{
    public function run(): void
    {
        $slaByPriority = SlaPolicy::query()
            ->whereNull('branch_id')
            ->whereNull('ticket_type_code')
            ->where('is_active', true)
            ->get()
            ->keyBy('priority');

        $types = [
            [
                'code' => 'connectivity_outage',
                'name_en' => 'Connectivity Outage',
                'name_fa' => 'قطع ارتباط',
                'default_department_code' => 'noc',
                'default_priority' => 'critical',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => true,
                'required_fields' => ['customer_id', 'related_radius_account'],
            ],
            [
                'code' => 'slow_speed',
                'name_en' => 'Slow Speed',
                'name_fa' => 'کندی سرعت',
                'default_department_code' => 'technical',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => true,
                'requires_finance_review' => false,
                'requires_radius_review' => true,
                'required_fields' => ['customer_id'],
            ],
            [
                'code' => 'intermittent_connection',
                'name_en' => 'Intermittent Connection',
                'name_fa' => 'ارتباط متناوب',
                'default_department_code' => 'technical',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => true,
                'expects_field_visit' => true,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id', 'customer_location'],
            ],
            [
                'code' => 'installation_request',
                'name_en' => 'Installation Request',
                'name_fa' => 'درخواست نصب',
                'default_department_code' => 'sales',
                'default_priority' => 'medium',
                'requires_customer' => false,
                'requires_site' => true,
                'expects_field_visit' => true,
                'requires_finance_review' => true,
                'requires_radius_review' => false,
                'required_fields' => ['customer_phone', 'customer_location'],
            ],
            [
                'code' => 'relocation',
                'name_en' => 'Service Relocation',
                'name_fa' => 'انتقال سرویس',
                'default_department_code' => 'technical',
                'default_priority' => 'medium',
                'requires_customer' => true,
                'requires_site' => true,
                'expects_field_visit' => true,
                'requires_finance_review' => true,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id', 'customer_location'],
            ],
            [
                'code' => 'billing_inquiry',
                'name_en' => 'Billing Inquiry',
                'name_fa' => 'استعلام صورتحساب',
                'default_department_code' => 'finance',
                'default_priority' => 'medium',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => true,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id'],
            ],
            [
                'code' => 'payment_dispute',
                'name_en' => 'Payment Dispute',
                'name_fa' => 'اختلاف پرداخت',
                'default_department_code' => 'finance',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => true,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id', 'related_payment_id'],
            ],
            [
                'code' => 'invoice_correction',
                'name_en' => 'Invoice Correction',
                'name_fa' => 'اصلاح فاکتور',
                'default_department_code' => 'finance',
                'default_priority' => 'medium',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => true,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id', 'related_invoice_id'],
            ],
            [
                'code' => 'package_change',
                'name_en' => 'Package Change',
                'name_fa' => 'تغییر پکیج',
                'default_department_code' => 'sales',
                'default_priority' => 'medium',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => true,
                'requires_radius_review' => true,
                'required_fields' => ['customer_id'],
            ],
            [
                'code' => 'account_suspension',
                'name_en' => 'Account Suspension',
                'name_fa' => 'تعلیق حساب',
                'default_department_code' => 'finance',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => true,
                'requires_radius_review' => true,
                'required_fields' => ['customer_id', 'related_radius_account'],
            ],
            [
                'code' => 'account_reactivation',
                'name_en' => 'Account Reactivation',
                'name_fa' => 'فعال‌سازی مجدد حساب',
                'default_department_code' => 'finance',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => true,
                'requires_radius_review' => true,
                'required_fields' => ['customer_id', 'related_radius_account'],
            ],
            [
                'code' => 'equipment_fault',
                'name_en' => 'Equipment Fault',
                'name_fa' => 'خرابی تجهیزات',
                'default_department_code' => 'technical',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => true,
                'expects_field_visit' => true,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id'],
            ],
            [
                'code' => 'equipment_replacement',
                'name_en' => 'Equipment Replacement',
                'name_fa' => 'تعویض تجهیزات',
                'default_department_code' => 'inventory',
                'default_priority' => 'medium',
                'requires_customer' => true,
                'requires_site' => true,
                'expects_field_visit' => true,
                'requires_finance_review' => true,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id'],
            ],
            [
                'code' => 'field_visit',
                'name_en' => 'Field Visit',
                'name_fa' => 'بازدید ساحوی',
                'default_department_code' => 'technical',
                'default_priority' => 'medium',
                'requires_customer' => true,
                'requires_site' => true,
                'expects_field_visit' => true,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id', 'customer_location'],
            ],
            [
                'code' => 'tower_issue',
                'name_en' => 'Tower / Site Issue',
                'name_fa' => 'مشکل تاور / سایت',
                'default_department_code' => 'noc',
                'default_priority' => 'critical',
                'requires_customer' => false,
                'requires_site' => true,
                'expects_field_visit' => true,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['related_tower'],
            ],
            [
                'code' => 'radius_account_issue',
                'name_en' => 'Radius Account Issue',
                'name_fa' => 'مشکل حساب رادیوس',
                'default_department_code' => 'noc',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => true,
                'required_fields' => ['customer_id', 'related_radius_account'],
            ],
            [
                'code' => 'whatsapp_general',
                'name_en' => 'WhatsApp General Inquiry',
                'name_fa' => 'استعلام عمومی واتساپ',
                'default_department_code' => 'customer_support',
                'default_priority' => 'medium',
                'requires_customer' => false,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['customer_phone'],
            ],
            [
                'code' => 'customer_complaint',
                'name_en' => 'Customer Complaint',
                'name_fa' => 'شکایت مشتری',
                'default_department_code' => 'customer_support',
                'default_priority' => 'high',
                'requires_customer' => true,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['customer_id', 'description'],
            ],
            [
                'code' => 'internal_request',
                'name_en' => 'Internal Request',
                'name_fa' => 'درخواست داخلی',
                'default_department_code' => 'management',
                'default_priority' => 'medium',
                'requires_customer' => false,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['subject', 'description'],
            ],
            [
                'code' => 'major_incident',
                'name_en' => 'Major Incident',
                'name_fa' => 'حادثه بزرگ',
                'default_department_code' => 'noc',
                'default_priority' => 'critical',
                'requires_customer' => false,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['subject', 'severity'],
            ],
            [
                'code' => 'coverage_inquiry',
                'name_en' => 'Coverage Inquiry',
                'name_fa' => 'استعلام پوشش',
                'default_department_code' => 'sales',
                'default_priority' => 'low',
                'requires_customer' => false,
                'requires_site' => true,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['customer_location'],
            ],
            [
                'code' => 'sales_followup',
                'name_en' => 'Sales Follow-up',
                'name_fa' => 'پیگیری فروش',
                'default_department_code' => 'sales',
                'default_priority' => 'low',
                'requires_customer' => false,
                'requires_site' => false,
                'expects_field_visit' => false,
                'requires_finance_review' => false,
                'requires_radius_review' => false,
                'required_fields' => ['customer_phone'],
            ],
        ];

        foreach ($types as $type) {
            $priority = $type['default_priority'];
            $slaId = $slaByPriority->get($priority)?->id;

            TicketType::query()->updateOrCreate(
                ['code' => $type['code']],
                array_merge($type, [
                    'is_active' => true,
                    'sla_policy_id' => $slaId,
                ])
            );
        }
    }
}
